In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import torch

from os.path import join
import SimpleITK as sitk



import common_utils.metrics as mt
import importlib
importlib.reload(mt)

In [2]:
def load_npy_from_med_file(med_file_path, debug=False):
    origin_image = sitk.ReadImage(med_file_path)
    original_im_arr=sitk.GetArrayFromImage(origin_image)
    original_shape=original_im_arr.shape
    pixel_spacing =origin_image.GetSpacing()
    if debug:
        print ('spacing',pixel_spacing)
        print ('shape',original_shape)
    return original_im_arr,original_shape,pixel_spacing

Load pred and gt pair

In [9]:
def evaluate(pred_dir,pred_format,gt_dir,gt_format, metrics_list =['Dice']):
    frames = ['ED','ES']
    pid_list =os.listdir(pred_dir)


    ## evaluate metric 
    n_classes = 4
    idx2cls_dict = {0:'BG',1:'LV',2:'MYO',3:'RV'}
    foreground_only=False


    metric= mt.runningMySegmentationScore(n_classes=n_classes,idx2cls_dict=idx2cls_dict,metrics_list=metrics_list)
    for frame in frames:
        for pid in sorted(pid_list):
            pred_path =join(pred_dir,pred_format.format(frame=frame,pid=pid))
            gt_path =join(gt_dir,gt_format.format(frame=frame,pid=pid))

            pred,shape,spacing = load_npy_from_med_file(pred_path)
            gt,shape,spacing = load_npy_from_med_file(gt_path)
            print ('evaluate ',str(pid),str(frame))
            metric.update(pid=pid+'_'+frame, preds=pred, gts=gt,
                                            voxel_spacing=spacing[::-1])

    print(metric.get_scores())
    df = metric.get_df()
    return df

In [4]:
UKBB_dfs={}

## Compute Metrics

In [6]:
## UKBB dataset



def evaluate_UKBB(method_name):
    pred_dir = '/vol/bitbucket/cc215/Projects/Cardiac_Multi_View_Segmentation/result/predict/{}/UKBB_test/LVSA/'.format(method_name)
    pred_format='{pid}/pred_{frame}.nii.gz'
   
    gt_dir ='/vol/medic02/users/wbai/data/cardiac_atlas/UKBB_2964/sa/test'
    gt_format='{pid}/label_sa_{frame}.nii.gz'
    df=evaluate(pred_dir,pred_format,gt_dir,gt_format)
    return df

method_name_list = [
                    'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power',
                    # 'baseline_Adam_finetune_v4_composite_50_independent_mse_adv',
                    # 'baseline_Adam_finetune_v4_composite_50_kl',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_random_random_select'
                    
                     ]
for method_name in method_name_list:
    df = evaluate_UKBB(method_name)
    UKBB_dfs[method_name] = df

evaluate  5050351 ED
evaluate  3580405 ED
evaluate  4117847 ED
evaluate  3609771 ED
evaluate  3331826 ED
evaluate  4067636 ED
evaluate  4482230 ED
evaluate  5057575 ED
evaluate  5458875 ED
evaluate  1714201 ED
evaluate  5548162 ED
evaluate  2485225 ED
evaluate  4280213 ED
evaluate  1750782 ED
evaluate  4272884 ED
evaluate  3896370 ED
evaluate  2043075 ED
evaluate  4785342 ED
evaluate  4383164 ED
evaluate  5851457 ED
evaluate  3538629 ED
evaluate  1356390 ED
evaluate  5249792 ED
evaluate  2623109 ED
evaluate  2341518 ED
evaluate  3525853 ED
evaluate  2707906 ED
evaluate  3536130 ED
evaluate  2194325 ED
evaluate  2512904 ED
evaluate  4317028 ED
evaluate  3648334 ED
evaluate  1499732 ED
evaluate  2422584 ED
evaluate  2664233 ED
evaluate  2666827 ED
evaluate  3548948 ED
evaluate  5377325 ED
evaluate  4011635 ED
evaluate  4476584 ED
evaluate  5080693 ED
evaluate  4000868 ED
evaluate  4276370 ED
evaluate  1557188 ED
evaluate  2999940 ED
evaluate  3978756 ED
evaluate  5724982 ED
evaluate  2407128 ED
evaluate  2169023 ED
evaluate  3989684 ED
evaluate  1165429 ED
evaluate  2222761 ED
evaluate  3828963 ED
evaluate  3269183 ED
evaluate  4964748 ED
evaluate  3330009 ED
evaluate  5039892 ED
evaluate  3706344 ED
evaluate  3195967 ED
evaluate  2811672 ED
evaluate  5833121 ED
evaluate  3594733 ED
evaluate  1944120 ED
evaluate  5054045 ED
evaluate  3448757 ED
evaluate  5414400 ED
evaluate  3134507 ED
evaluate  4434682 ED
evaluate  2151563 ED
evaluate  3951088 ED
evaluate  2562883 ED
evaluate  2607669 ED
evaluate  3202301 ED
evaluate  1671247 ED
evaluate  1023154 ED
evaluate  5212935 ED
evaluate  1733743 ED
evaluate  4871327 ED
evaluate  2385296 ED
evaluate  1850061 ED
evaluate  3994007 ED
evaluate  1272885 ED
evaluate  1995221 ED
evaluate  4484123 ED
evaluate  3760161 ED
evaluate  4569397 ED
evaluate  2951040 ED
evaluate  1228801 ED
evaluate  2437732 ED
evaluate  4128563 ED
evaluate  4051914 ED
evaluate  5163185 ED
evaluate  1316244 ED
evaluate  4285228 ED
evaluate  3891671 ED
evaluate  4354745 ED
evaluate  1693095 ED
evaluate  5228557 ED
evaluate  5068235 ED
evaluate  2027249 ED
evaluate  5444856 ED
evaluate  3846824 ED
evaluate  4509999 ED
evaluate  2472035 ED
evaluate  3637945 ED
evaluate  4936676 ED
evaluate  1482910 ED
evaluate  5695393 ED
evaluate  4942913 ED
evaluate  4426958 ED
evaluate  2278341 ED
evaluate  5374026 ED
evaluate  4177365 ED
evaluate  5993613 ED
evaluate  3510903 ED
evaluate  5737172 ED
evaluate  4256185 ED
evaluate  2640874 ED
evaluate  1848251 ED
evaluate  3330394 ED
evaluate  4052319 ED
evaluate  2310249 ED
evaluate  5757171 ED
evaluate  2659978 ED
evaluate  5157682 ED
evaluate  1012733 ED
evaluate  2372211 ED
evaluate  1756156 ED
evaluate  2515439 ED
evaluate  2538647 ED
evaluate  5138953 ED
evaluate  1430567 ED
evaluate  2044027 ED
evaluate  1798472 ED
evaluate  4834778 ED
evaluate  4369704 ED
evaluate  1493022 ED
evaluate  4335569 ED
evaluate  5937668 ED
evaluate  2757900 ED
evaluate  5170509 ED
evaluate  1441230 ED
evaluate  3280143 ED
evaluate  3984439 ED
evaluate  1720462 ED
evaluate  5687952 ED
evaluate  5530691 ED
evaluate  4990574 ED
evaluate  5101726 ED
evaluate  2336430 ED
evaluate  2045677 ED
evaluate  2223083 ED
evaluate  4690326 ED
evaluate  4096850 ED
evaluate  1075740 ED
evaluate  2860204 ED
evaluate  2203229 ED
evaluate  5568022 ED
evaluate  2552693 ED
evaluate  2502177 ED
evaluate  3374340 ED
evaluate  2020435 ED
evaluate  5286543 ED
evaluate  2059070 ED
evaluate  1818985 ED
evaluate  3694333 ED
evaluate  1217350 ED
evaluate  3304378 ED
evaluate  4295804 ED
evaluate  5841964 ED
evaluate  2789363 ED
evaluate  1776185 ED
evaluate  3836752 ED
evaluate  5935420 ED
evaluate  2934651 ED
evaluate  5395263 ED
evaluate  2559444 ED
evaluate  2156834 ED
evaluate  4602568 ED
evaluate  4351982 ED
evaluate  2935490 ED
evaluate  5002669 ED
evaluate  3899275 ED
evaluate  4158590 ED
evaluate  2126843 ED
evaluate  3284039 ED
evaluate  3084819 ED
evaluate  1392176 ED
evaluate  2072980 ED
evaluate  5293109 ED
evaluate  1336389 ED
evaluate  3162788 ED
evaluate  4966320 ED
evaluate  2895601 ED
evaluate  2863554 ED
evaluate  5025534 ED
evaluate  2240685 ED
evaluate  5907006 ED
evaluate  2607400 ED
evaluate  1385247 ED
evaluate  1761514 ED
evaluate  5905560 ED
evaluate  1406685 ED
evaluate  3523224 ED
evaluate  5698859 ED
evaluate  5131909 ED
evaluate  1060251 ED
evaluate  5778257 ED
evaluate  3192383 ED
evaluate  2836895 ED
evaluate  5715142 ED
evaluate  3199315 ED
evaluate  5245704 ED
evaluate  1837361 ED
evaluate  5044516 ED
evaluate  1069713 ED
evaluate  3001465 ED
evaluate  4116315 ED
evaluate  2109140 ED
evaluate  1101778 ED
evaluate  5732320 ED
evaluate  3370617 ED
evaluate  4103976 ED
evaluate  4091272 ED
evaluate  2915873 ED
evaluate  1937886 ED
evaluate  1320559 ED
evaluate  3701901 ED
evaluate  3166304 ED
evaluate  4634116 ED
evaluate  4074667 ED
evaluate  5019657 ED
evaluate  3937205 ED
evaluate  5199258 ED
evaluate  5607540 ED
evaluate  2244984 ED
evaluate  2565973 ED
evaluate  2387306 ED
evaluate  1526531 ED
evaluate  3081983 ED
evaluate  1414341 ED
evaluate  3346980 ED
evaluate  5607967 ED
evaluate  2675844 ED
evaluate  1740251 ED
evaluate  4510446 ED
evaluate  3283349 ED
evaluate  4638074 ED
evaluate  1810919 ED
evaluate  2095958 ED
evaluate  2679335 ED
evaluate  4496986 ED
evaluate  2190960 ED
evaluate  3251757 ED
evaluate  4069958 ED
evaluate  1660579 ED
evaluate  4557204 ED
evaluate  3311664 ED
evaluate  2386227 ED
evaluate  5966365 ED
evaluate  1236028 ED
evaluate  5436983 ED
evaluate  3863156 ED
evaluate  1959984 ED
evaluate  3397404 ED
evaluate  4532639 ED
evaluate  5941273 ED
evaluate  2795071 ED
evaluate  3250374 ED
evaluate  5740286 ED
evaluate  3283812 ED
evaluate  2416418 ED
evaluate  1786613 ED
evaluate  4539172 ED
evaluate  5240735 ED
evaluate  3897310 ED
evaluate  1486164 ED
evaluate  1567848 ED
evaluate  2963856 ED
evaluate  3183348 ED
evaluate  2800369 ED
evaluate  4665264 ED
evaluate  5157511 ED
evaluate  1942171 ED
evaluate  4065853 ED
evaluate  2627103 ED
evaluate  2747104 ED
evaluate  3407026 ED
evaluate  4532588 ED
evaluate  5552562 ED
evaluate  5502286 ED
evaluate  2689795 ED
evaluate  1852305 ED
evaluate  1078494 ED
evaluate  3899670 ED
evaluate  1197429 ED
evaluate  4039940 ED
evaluate  3869569 ED
evaluate  1171269 ED
evaluate  4746266 ED
evaluate  2358347 ED
evaluate  4871966 ED
evaluate  1133396 ED
evaluate  3155876 ED
evaluate  3527105 ED
evaluate  2885412 ED
evaluate  4118184 ED
evaluate  3436683 ED
evaluate  4343652 ED
evaluate  4075789 ED
evaluate  5620442 ED
evaluate  3174829 ED
evaluate  5346894 ED
evaluate  3177186 ED
evaluate  1952615 ED
evaluate  5911313 ED
evaluate  5718152 ED
evaluate  1889932 ED
evaluate  5299052 ED
evaluate  4672619 ED
evaluate  1492196 ED
evaluate  2778054 ED
evaluate  5945808 ED
evaluate  4683971 ED
evaluate  4462955 ED
evaluate  5742676 ED
evaluate  3845676 ED
evaluate  1752456 ED
evaluate  4793421 ED
evaluate  5222429 ED
evaluate  2570292 ED
evaluate  1686650 ED
evaluate  3976972 ED
evaluate  1381676 ED
evaluate  1399699 ED
evaluate  3254510 ED
evaluate  5933111 ED
evaluate  1342552 ED
evaluate  1739969 ED
evaluate  1885175 ED
evaluate  2713608 ED
evaluate  5250360 ED
evaluate  5770082 ED
evaluate  2510664 ED
evaluate  1203290 ED
evaluate  3127423 ED
evaluate  2862731 ED
evaluate  2835355 ED
evaluate  1819321 ED
evaluate  4699356 ED
evaluate  2388455 ED
evaluate  5927105 ED
evaluate  1817421 ED
evaluate  4689126 ED
evaluate  1223452 ED
evaluate  1255220 ED
evaluate  5496126 ED
evaluate  4452493 ED
evaluate  1128392 ED
evaluate  2711900 ED
evaluate  1828859 ED
evaluate  3453241 ED
evaluate  5677292 ED
evaluate  1098180 ED
evaluate  3960905 ED
evaluate  3910361 ED
evaluate  5561041 ED
evaluate  4394777 ED
evaluate  2882320 ED
evaluate  3804564 ED
evaluate  3088472 ED
evaluate  2176503 ED
evaluate  5536458 ED
evaluate  3439192 ED
evaluate  5291567 ED
evaluate  5266847 ED
evaluate  3154846 ED
evaluate  5526494 ED
evaluate  1091016 ED
evaluate  1184095 ED
evaluate  3757564 ED
evaluate  5116048 ED
evaluate  5417562 ED
evaluate  4174335 ED
evaluate  1960755 ED
evaluate  1718912 ED
evaluate  4360896 ED
evaluate  4977197 ED
evaluate  1413621 ED
evaluate  1376252 ED
evaluate  4884550 ED
evaluate  2312900 ED
evaluate  5567447 ED
evaluate  4464785 ED
evaluate  1665903 ED
evaluate  1712657 ED
evaluate  2850852 ED
evaluate  2957734 ED
evaluate  5002235 ED
evaluate  5875035 ED
evaluate  5627046 ED
evaluate  3508416 ED
evaluate  5085921 ED
evaluate  4053191 ED
evaluate  1404425 ED
evaluate  4175711 ED
evaluate  3920791 ED
evaluate  5452871 ED
evaluate  5192416 ED
evaluate  5584255 ED
evaluate  3705666 ED
evaluate  3003458 ED
evaluate  3457640 ED
evaluate  5760049 ED
evaluate  4035797 ED
evaluate  5496639 ED
evaluate  2132639 ED
evaluate  1633918 ED
evaluate  1773691 ED
evaluate  3181101 ED
evaluate  3586968 ED
evaluate  3547512 ED
evaluate  4856763 ED
evaluate  3210743 ED
evaluate  3172570 ED
evaluate  4965575 ED
evaluate  5235352 ED
evaluate  2621392 ED
evaluate  5240046 ED
evaluate  5246983 ED
evaluate  1284733 ED
evaluate  4565045 ED
evaluate  1147822 ED
evaluate  3696889 ED
evaluate  5170374 ED
evaluate  1243563 ED
evaluate  2507837 ED
evaluate  5619946 ED
evaluate  3584243 ED
evaluate  5435570 ED
evaluate  3046273 ED
evaluate  2719769 ED
evaluate  1452200 ED
evaluate  3519146 ED
evaluate  4313555 ED
evaluate  5474967 ED
evaluate  2846236 ED
evaluate  2769460 ED
evaluate  1755006 ED
evaluate  4695746 ED
evaluate  3264964 ED
evaluate  1500066 ED
evaluate  2158349 ED
evaluate  1368479 ED
evaluate  4453391 ED
evaluate  4499784 ED
evaluate  2456454 ED
evaluate  2180494 ED
evaluate  1286921 ED
evaluate  5546704 ED
evaluate  5002026 ED
evaluate  2011092 ED
evaluate  5109071 ED
evaluate  4030451 ED
evaluate  3336016 ED
evaluate  2466206 ED
evaluate  3945804 ED
evaluate  3561029 ED
evaluate  1971072 ED
evaluate  5097338 ED
evaluate  4847930 ED
evaluate  2287734 ED
evaluate  3523132 ED
evaluate  3905827 ED
evaluate  4298627 ED
evaluate  5679676 ED
evaluate  5320331 ED
evaluate  3009283 ED
evaluate  5710507 ED
evaluate  4254960 ED
evaluate  4799079 ED
evaluate  1717511 ED
evaluate  4829457 ED
evaluate  1057856 ED
evaluate  3930691 ED
evaluate  1950994 ED
evaluate  4749888 ED
evaluate  2842310 ED
evaluate  5564729 ED
evaluate  2218937 ED
evaluate  5186495 ED
evaluate  4120636 ED
evaluate  1482234 ED
evaluate  2606880 ED
evaluate  3448426 ED
evaluate  3524864 ED
evaluate  1633714 ED
evaluate  5674057 ED
evaluate  5624627 ED
evaluate  1234426 ED
evaluate  3290297 ED
evaluate  5613253 ED
evaluate  2405229 ED
evaluate  5257069 ED
evaluate  5727515 ED
evaluate  3029823 ED
evaluate  4467984 ED
evaluate  3163833 ED
evaluate  1690999 ED
evaluate  2165793 ED
evaluate  1429487 ED
evaluate  5963795 ED
evaluate  4348208 ED
evaluate  2321480 ED
evaluate  1423649 ED
evaluate  4197662 ED
evaluate  4694916 ED
evaluate  5565637 ED
evaluate  2947553 ED
evaluate  5861160 ED
evaluate  1410774 ED
evaluate  3277565 ED
evaluate  1043602 ED
evaluate  4419186 ED
evaluate  5006342 ED
evaluate  3874614 ED
evaluate  2629492 ED
evaluate  2978821 ED
evaluate  5867225 ED
evaluate  2227697 ED
evaluate  2308905 ED
evaluate  5397773 ED
evaluate  2111295 ED
evaluate  3472689 ED
evaluate  2123768 ED
evaluate  2733057 ED
evaluate  3850183 ED
evaluate  2539240 ED
evaluate  2399034 ED
evaluate  2166947 ED
evaluate  4863090 ED
evaluate  5770230 ED
evaluate  5373171 ED
evaluate  3177532 ED
evaluate  4616257 ED
evaluate  3363786 ED
evaluate  3485327 ED
evaluate  5128634 ED
evaluate  4971090 ED
evaluate  4888829 ED
evaluate  1616987 ED
evaluate  3693077 ED
evaluate  4946206 ED
evaluate  3037492 ED
evaluate  4626132 ED
evaluate  1723417 ED
evaluate  5901468 ED
evaluate  5363357 ED
evaluate  3870220 ED
evaluate  4504148 ED
evaluate  3303468 ED
evaluate  4003979 ED
evaluate  4590342 ED
evaluate  2905421 ED
evaluate  1499492 ED
evaluate  4221724 ED
evaluate  4505217 ED
evaluate  1958134 ED
evaluate  2833069 ED
evaluate  3341039 ED
evaluate  1194700 ED
evaluate  4446431 ED
evaluate  4174252 ED
evaluate  5026801 ED
evaluate  5401156 ED
evaluate  3487392 ED
evaluate  1297177 ED
evaluate  1120293 ED
evaluate  2981407 ED
evaluate  2613724 ED
evaluate  5295985 ED
evaluate  1457380 ED
evaluate  4238078 ED
evaluate  2003250 ED
evaluate  5346113 ED
evaluate  3931418 ED
evaluate  2550649 ED
evaluate  5984672 ED
evaluate  3903230 ED
evaluate  1977272 ED
evaluate  5558279 ED
evaluate  3489356 ED
evaluate  5969779 ED
evaluate  4371240 ED
evaluate  3713026 ED
evaluate  3339152 ED
evaluate  3644483 ED
evaluate  5454697 ED
evaluate  2320123 ED
evaluate  5765012 ED
evaluate  5050351 ES
evaluate  3580405 ES
evaluate  4117847 ES
evaluate  3609771 ES
evaluate  3331826 ES
evaluate  4067636 ES
evaluate  4482230 ES
evaluate  5057575 ES
evaluate  5458875 ES
evaluate  1714201 ES
evaluate  5548162 ES
evaluate  2485225 ES
evaluate  4280213 ES
evaluate  1750782 ES
evaluate  4272884 ES
evaluate  3896370 ES
evaluate  2043075 ES
evaluate  4785342 ES
evaluate  4383164 ES
evaluate  5851457 ES
evaluate  3538629 ES
evaluate  1356390 ES
evaluate  5249792 ES
evaluate  2623109 ES
evaluate  2341518 ES
evaluate  3525853 ES
evaluate  2707906 ES
evaluate  3536130 ES
evaluate  2194325 ES
evaluate  2512904 ES
evaluate  4317028 ES
evaluate  3648334 ES
evaluate  1499732 ES
evaluate  2422584 ES
evaluate  2664233 ES
evaluate  2666827 ES
evaluate  3548948 ES
evaluate  5377325 ES
evaluate  4011635 ES
evaluate  4476584 ES
evaluate  5080693 ES
evaluate  4000868 ES
evaluate  4276370 ES
evaluate  1557188 ES
evaluate  2999940 ES
evaluate  3978756 ES
evaluate  5724982 ES
evaluate  2407128 ES
evaluate  2169023 ES
evaluate  3989684 ES
evaluate  1165429 ES
evaluate  2222761 ES
evaluate  3828963 ES
evaluate  3269183 ES
evaluate  4964748 ES
evaluate  3330009 ES
evaluate  5039892 ES
evaluate  3706344 ES
evaluate  3195967 ES
evaluate  2811672 ES
evaluate  5833121 ES
evaluate  3594733 ES
evaluate  1944120 ES
evaluate  5054045 ES
evaluate  3448757 ES
evaluate  5414400 ES
evaluate  3134507 ES
evaluate  4434682 ES
evaluate  2151563 ES
evaluate  3951088 ES
evaluate  2562883 ES
evaluate  2607669 ES
evaluate  3202301 ES
evaluate  1671247 ES
evaluate  1023154 ES
evaluate  5212935 ES
evaluate  1733743 ES
evaluate  4871327 ES
evaluate  2385296 ES
evaluate  1850061 ES
evaluate  3994007 ES
evaluate  1272885 ES
evaluate  1995221 ES
evaluate  4484123 ES
evaluate  3760161 ES
evaluate  4569397 ES
evaluate  2951040 ES
evaluate  1228801 ES
evaluate  2437732 ES
evaluate  4128563 ES
evaluate  4051914 ES
evaluate  5163185 ES
evaluate  1316244 ES
evaluate  4285228 ES
evaluate  3891671 ES
evaluate  4354745 ES
evaluate  1693095 ES
evaluate  5228557 ES
evaluate  5068235 ES
evaluate  2027249 ES
evaluate  5444856 ES
evaluate  3846824 ES
evaluate  4509999 ES
evaluate  2472035 ES
evaluate  3637945 ES
evaluate  4936676 ES
evaluate  1482910 ES
evaluate  5695393 ES
evaluate  4942913 ES
evaluate  4426958 ES
evaluate  2278341 ES
evaluate  5374026 ES
evaluate  4177365 ES
evaluate  5993613 ES
evaluate  3510903 ES
evaluate  5737172 ES
evaluate  4256185 ES
evaluate  2640874 ES
evaluate  1848251 ES
evaluate  3330394 ES
evaluate  4052319 ES
evaluate  2310249 ES
evaluate  5757171 ES
evaluate  2659978 ES
evaluate  5157682 ES
evaluate  1012733 ES
evaluate  2372211 ES
evaluate  1756156 ES
evaluate  2515439 ES
evaluate  2538647 ES
evaluate  5138953 ES
evaluate  1430567 ES
evaluate  2044027 ES
evaluate  1798472 ES
evaluate  4834778 ES
evaluate  4369704 ES
evaluate  1493022 ES
evaluate  4335569 ES
evaluate  5937668 ES
evaluate  2757900 ES
evaluate  5170509 ES
evaluate  1441230 ES
evaluate  3280143 ES
evaluate  3984439 ES
evaluate  1720462 ES
evaluate  5687952 ES
evaluate  5530691 ES
evaluate  4990574 ES
evaluate  5101726 ES
evaluate  2336430 ES
evaluate  2045677 ES
evaluate  2223083 ES
evaluate  4690326 ES
evaluate  4096850 ES
evaluate  1075740 ES
evaluate  2860204 ES
evaluate  2203229 ES
evaluate  5568022 ES
evaluate  2552693 ES
evaluate  2502177 ES
evaluate  3374340 ES
evaluate  2020435 ES
evaluate  5286543 ES
evaluate  2059070 ES
evaluate  1818985 ES
evaluate  3694333 ES
evaluate  1217350 ES
evaluate  3304378 ES
evaluate  4295804 ES
evaluate  5841964 ES
evaluate  2789363 ES
evaluate  1776185 ES
evaluate  3836752 ES
evaluate  5935420 ES
evaluate  2934651 ES
evaluate  5395263 ES
evaluate  2559444 ES
evaluate  2156834 ES
evaluate  4602568 ES
evaluate  4351982 ES
evaluate  2935490 ES
evaluate  5002669 ES
evaluate  3899275 ES
evaluate  4158590 ES
evaluate  2126843 ES
evaluate  3284039 ES
evaluate  3084819 ES
evaluate  1392176 ES
evaluate  2072980 ES
evaluate  5293109 ES
evaluate  1336389 ES
evaluate  3162788 ES
evaluate  4966320 ES
evaluate  2895601 ES
evaluate  2863554 ES
evaluate  5025534 ES
evaluate  2240685 ES
evaluate  5907006 ES
evaluate  2607400 ES
evaluate  1385247 ES
evaluate  1761514 ES
evaluate  5905560 ES
evaluate  1406685 ES
evaluate  3523224 ES
evaluate  5698859 ES
evaluate  5131909 ES
evaluate  1060251 ES
evaluate  5778257 ES
evaluate  3192383 ES
evaluate  2836895 ES
evaluate  5715142 ES
evaluate  3199315 ES
evaluate  5245704 ES
evaluate  1837361 ES
evaluate  5044516 ES
evaluate  1069713 ES
evaluate  3001465 ES
evaluate  4116315 ES
evaluate  2109140 ES
evaluate  1101778 ES
evaluate  5732320 ES
evaluate  3370617 ES
evaluate  4103976 ES
evaluate  4091272 ES
evaluate  2915873 ES
evaluate  1937886 ES
evaluate  1320559 ES
evaluate  3701901 ES
evaluate  3166304 ES
evaluate  4634116 ES
evaluate  4074667 ES
evaluate  5019657 ES
evaluate  3937205 ES
evaluate  5199258 ES
evaluate  5607540 ES
evaluate  2244984 ES
evaluate  2565973 ES
evaluate  2387306 ES
evaluate  1526531 ES
evaluate  3081983 ES
evaluate  1414341 ES
evaluate  3346980 ES
evaluate  5607967 ES
evaluate  2675844 ES
evaluate  1740251 ES
evaluate  4510446 ES
evaluate  3283349 ES
evaluate  4638074 ES
evaluate  1810919 ES
evaluate  2095958 ES
evaluate  2679335 ES
evaluate  4496986 ES
evaluate  2190960 ES
evaluate  3251757 ES
evaluate  4069958 ES
evaluate  1660579 ES
evaluate  4557204 ES
evaluate  3311664 ES
evaluate  2386227 ES
evaluate  5966365 ES
evaluate  1236028 ES
evaluate  5436983 ES
evaluate  3863156 ES
evaluate  1959984 ES
evaluate  3397404 ES
evaluate  4532639 ES
evaluate  5941273 ES
evaluate  2795071 ES
evaluate  3250374 ES
evaluate  5740286 ES
evaluate  3283812 ES
evaluate  2416418 ES
evaluate  1786613 ES
evaluate  4539172 ES
evaluate  5240735 ES
evaluate  3897310 ES
evaluate  1486164 ES
evaluate  1567848 ES
evaluate  2963856 ES
evaluate  3183348 ES
evaluate  2800369 ES
evaluate  4665264 ES
evaluate  5157511 ES
evaluate  1942171 ES
evaluate  4065853 ES
evaluate  2627103 ES
evaluate  2747104 ES
evaluate  3407026 ES
evaluate  4532588 ES
evaluate  5552562 ES
evaluate  5502286 ES
evaluate  2689795 ES
evaluate  1852305 ES
evaluate  1078494 ES
evaluate  3899670 ES
evaluate  1197429 ES
evaluate  4039940 ES
evaluate  3869569 ES
evaluate  1171269 ES
evaluate  4746266 ES
evaluate  2358347 ES
evaluate  4871966 ES
evaluate  1133396 ES
evaluate  3155876 ES
evaluate  3527105 ES
evaluate  2885412 ES
evaluate  4118184 ES
evaluate  3436683 ES
evaluate  4343652 ES
evaluate  4075789 ES
evaluate  5620442 ES
evaluate  3174829 ES
evaluate  5346894 ES
evaluate  3177186 ES
evaluate  1952615 ES
evaluate  5911313 ES
evaluate  5718152 ES
evaluate  1889932 ES
evaluate  5299052 ES
evaluate  4672619 ES
evaluate  1492196 ES
evaluate  2778054 ES
evaluate  5945808 ES
evaluate  4683971 ES
evaluate  4462955 ES
evaluate  5742676 ES
evaluate  3845676 ES
evaluate  1752456 ES
evaluate  4793421 ES
evaluate  5222429 ES
evaluate  2570292 ES
evaluate  1686650 ES
evaluate  3976972 ES
evaluate  1381676 ES
evaluate  1399699 ES
evaluate  3254510 ES
evaluate  5933111 ES
evaluate  1342552 ES
evaluate  1739969 ES
evaluate  1885175 ES
evaluate  2713608 ES
evaluate  5250360 ES
evaluate  5770082 ES
evaluate  2510664 ES
evaluate  1203290 ES
evaluate  3127423 ES
evaluate  2862731 ES
evaluate  2835355 ES
evaluate  1819321 ES
evaluate  4699356 ES
evaluate  2388455 ES
evaluate  5927105 ES

In [19]:
for k, df in UKBB_dfs.items():
    print(k)
    print (df.describe())

UKBB_p_value= mt.p_value_test(reference_df = UKBB_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select'],
                            test_df= UKBB_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power'])
print ('UKBB',UKBB_p_value)

baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select
       BG_Dice      LV_Dice     MYO_Dice      RV_Dice
count   1200.0  1200.000000  1200.000000  1200.000000
mean       0.0     0.935863     0.876354     0.896539
std        0.0     0.040719     0.033119     0.045701
min        0.0     0.587556     0.646893     0.669689
25%        0.0     0.923632     0.859850     0.875211
50%        0.0     0.944186     0.882942     0.905714
75%        0.0     0.964928     0.899371     0.931107
max        0.0     0.985154     0.937877     0.965549
baseline_Adam_finetune_v4_composite_50_chain_mse_random_random_select
       BG_Dice      LV_Dice     MYO_Dice      RV_Dice
count   1200.0  1200.000000  1200.000000  1200.000000
mean       0.0     0.936882     0.874823     0.897482
std        0.0     0.040229     0.034274     0.045395
min        0.0     0.575866     0.665528     0.663078
25%        0.0     0.923983     0.857367     0.874983
50%        0.0     0.945966     0.880249     0.905450
75%        0.0     0.964206     0.899570     0.931739
max        0.0     0.984258     0.937663     0.968827
UKBB {'LV_Dice': '0.0044', 'MYO_Dice': '0.0000', 'RV_Dice': '0.0090'}

In [7]:
df.describe()

       BG_Dice      LV_Dice     MYO_Dice      RV_Dice
count   1200.0  1200.000000  1200.000000  1200.000000
mean       0.0     0.935955     0.873186     0.896453
std        0.0     0.040822     0.031172     0.045620
min        0.0     0.585522     0.690719     0.680826
25%        0.0     0.923705     0.856000     0.874371
50%        0.0     0.944210     0.877957     0.905163
75%        0.0     0.964748     0.895255     0.931143
max        0.0     0.984613     0.935025     0.966166

In [9]:
ACDC_dfs={}

In [11]:
## ACDC
ACDC_dfs={}
def evaluate_ACDC(method_name):
    pred_dir = '/vol/bitbucket/cc215/Projects/Cardiac_Multi_View_Segmentation/result/predict/{}/ACDC_all/LVSA/'.format(method_name)
    pred_format='{pid}/pred_{frame}.nrrd'
    gt_dir ='/vol/biomedic3/cc215/data/ACDC/bias_corrected_and_normalized/patient_wise'
    gt_format='{pid}/{frame}_seg.nrrd'
    df=evaluate(pred_dir,pred_format,gt_dir,gt_format)
    return df

method_name_list = [
                    'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power',
                    # 'baseline_Adam_finetune_v4_composite_50_independent_mse_adv',
                    # 'baseline_Adam_finetune_v4_composite_50_kl',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_random_random_select'

                     ]
for method_name in method_name_list:
    df = evaluate_ACDC(method_name)
    ACDC_dfs[method_name] = df

evaluate  001 ED
evaluate  002 ED
evaluate  003 ED
evaluate  004 ED
evaluate  005 ED
evaluate  006 ED
evaluate  007 ED
evaluate  008 ED
evaluate  009 ED
evaluate  010 ED
evaluate  011 ED
evaluate  012 ED
evaluate  013 ED
evaluate  014 ED
evaluate  015 ED
evaluate  016 ED
evaluate  017 ED
evaluate  018 ED
evaluate  019 ED
evaluate  020 ED
evaluate  021 ED
evaluate  022 ED
evaluate  023 ED
evaluate  024 ED
evaluate  025 ED
evaluate  026 ED
evaluate  027 ED
evaluate  028 ED
evaluate  029 ED
evaluate  030 ED
evaluate  031 ED
evaluate  032 ED
evaluate  033 ED
evaluate  034 ED
evaluate  035 ED
evaluate  036 ED
evaluate  037 ED
evaluate  038 ED
evaluate  039 ED
evaluate  040 ED
evaluate  041 ED
evaluate  042 ED
evaluate  043 ED
evaluate  044 ED
evaluate  045 ED
evaluate  046 ED
evaluate  047 ED
evaluate  048 ED
evaluate  049 ED
evaluate  050 ED
evaluate  051 ED
evaluate  052 ED
evaluate  053 ED
evaluate  054 ED
evaluate  055 ED
evaluate  056 ED
evaluate  057 ED
evaluate  058 ED
evaluate  059 ED
evaluate  060 ED
evaluate  061 ED
evaluate  062 ED
evaluate  063 ED
evaluate  064 ED
evaluate  065 ED
evaluate  066 ED
evaluate  067 ED
evaluate  068 ED
evaluate  069 ED
evaluate  070 ED
evaluate  071 ED
evaluate  072 ED
evaluate  073 ED
evaluate  074 ED
evaluate  075 ED
evaluate  076 ED
evaluate  077 ED
evaluate  078 ED
evaluate  079 ED
evaluate  080 ED
evaluate  081 ED
evaluate  082 ED
evaluate  083 ED
evaluate  084 ED
evaluate  085 ED
evaluate  086 ED
evaluate  087 ED
evaluate  088 ED
evaluate  089 ED
evaluate  090 ED
evaluate  091 ED
evaluate  092 ED
evaluate  093 ED
evaluate  094 ED
evaluate  095 ED
evaluate  096 ED
evaluate  097 ED
evaluate  098 ED
evaluate  099 ED
evaluate  100 ED
evaluate  001 ES
evaluate  002 ES
evaluate  003 ES
evaluate  004 ES
evaluate  005 ES
evaluate  006 ES
evaluate  007 ES
evaluate  008 ES
evaluate  009 ES
evaluate  010 ES
evaluate  011 ES
evaluate  012 ES
evaluate  013 ES
evaluate  014 ES
evaluate  015 ES
evaluate  016 ES
evaluate  017 ES
evaluate  018 ES
evaluate  019 ES
evaluate  020 ES
evaluate  021 ES
evaluate  022 ES
evaluate  023 ES
evaluate  024 ES
evaluate  025 ES
evaluate  026 ES
evaluate  027 ES
evaluate  028 ES
evaluate  029 ES
evaluate  030 ES
evaluate  031 ES
evaluate  032 ES
evaluate  033 ES
evaluate  034 ES
evaluate  035 ES
evaluate  036 ES
evaluate  037 ES
evaluate  038 ES
evaluate  039 ES
evaluate  040 ES
evaluate  041 ES
evaluate  042 ES
evaluate  043 ES
evaluate  044 ES
evaluate  045 ES
evaluate  046 ES
evaluate  047 ES
evaluate  048 ES
evaluate  049 ES
evaluate  050 ES
evaluate  051 ES
evaluate  052 ES
evaluate  053 ES
evaluate  054 ES
evaluate  055 ES
evaluate  056 ES
evaluate  057 ES
evaluate  058 ES
evaluate  059 ES
evaluate  060 ES
evaluate  061 ES
evaluate  062 ES
evaluate  063 ES
evaluate  064 ES
evaluate  065 ES
evaluate  066 ES
evaluate  067 ES
evaluate  068 ES
evaluate  069 ES
evaluate  070 ES
evaluate  071 ES
evaluate  072 ES
evaluate  073 ES
evaluate  074 ES
evaluate  075 ES
evaluate  076 ES
evaluate  077 ES
evaluate  078 ES
evaluate  079 ES
evaluate  080 ES
evaluate  081 ES
evaluate  082 ES
evaluate  083 ES
evaluate  084 ES
evaluate  085 ES
evaluate  086 ES
evaluate  087 ES
evaluate  088 ES
evaluate  089 ES
evaluate  090 ES
evaluate  091 ES
evaluate  092 ES
evaluate  093 ES
evaluate  094 ES
evaluate  095 ES
evaluate  096 ES
evaluate  097 ES
evaluate  098 ES
evaluate  099 ES
evaluate  100 ES
({'BG_Dice_mean': 0.0, 'BG_Dice_std': 0.0, 'LV_Dice_mean': 0.9060041920220282, 'LV_Dice_std': 0.0767645884321402, 'MYO_Dice_mean': 0.808788828779763, 'MYO_Dice_std': 0.06098981703739351, 'RV_Dice_mean': 0.8404507171423465, 'RV_Dice_std': 0.09433315011969275}, [['0.000', '0.906', '0.809', '0.840'], ['0.000', '0.077', '0.061', '0.094']], ['BG_Dice', 'LV_Dice', 'MYO_Dice', 'RV_Dice'])

In [12]:
acdc_p_value= mt.p_value_test(reference_df = ACDC_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select'],
                            test_df= ACDC_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_random_random_select'])
print ('ACDC',acdc_p_value)

ACDC {'LV_Dice': '0.0026', 'MYO_Dice': '0.0000', 'RV_Dice': '0.1207'}

In [12]:
for k, df in ACDC_dfs.items():
    print (k)
    print(df.describe())

baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power
       BG_Dice     LV_Dice    MYO_Dice     RV_Dice
count    200.0  200.000000  200.000000  200.000000
mean       0.0    0.906004    0.808789    0.840451
std        0.0    0.076957    0.061143    0.094570
min        0.0    0.442243    0.515490    0.425032
25%        0.0    0.889149    0.782215    0.793428
50%        0.0    0.928966    0.823190    0.858517
75%        0.0    0.955271    0.852426    0.911326
max        0.0    0.973052    0.887758    0.955946

In [12]:
ACDC_dfs

{'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power':     patient_id  BG_Dice   LV_Dice  MYO_Dice   RV_Dice
 0       001_ED      0.0  0.946837  0.778550  0.877727
 1       002_ED      0.0  0.943515  0.733577  0.921918
 2       003_ED      0.0  0.965310  0.833796  0.899515
 3       004_ED      0.0  0.956802  0.783946  0.856934
 4       005_ED      0.0  0.969773  0.778315  0.857708
 ..         ...      ...       ...       ...       ...
 195     096_ES      0.0  0.897972  0.799145  0.893008
 196     097_ES      0.0  0.759555  0.745114  0.842224
 197     098_ES      0.0  0.752113  0.764306  0.783759
 198     099_ES      0.0  0.868654  0.737990  0.875208
 199     100_ES      0.0  0.844737  0.860020  0.803879

 [200 rows x 5 columns],
 'baseline_Adam_finetune_v4_composite_50_independent_mse_adv':     patient_id  BG_Dice   LV_Dice  MYO_Dice   RV_Dice
 0       001_ED      0.0  0.952266  0.801062  0.881033
 1       002_ED      0.0  0.960534  0.808588  0.936918
 2       003_ED      0.0  0.965839  0.847537  0.906204
 3       004_ED      0.0  0.966089  0.847007  0.890715
 4       005_ED      0.0  0.962721  0.841851  0.900808
 ..         ...      ...       ...       ...       ...
 195     096_ES      0.0  0.874456  0.811543  0.896603
 196     097_ES      0.0  0.882087  0.804888  0.795862
 197     098_ES      0.0  0.807567  0.815980  0.920057
 198     099_ES      0.0  0.867302  0.779059  0.879419
 199     100_ES      0.0  0.851664  0.869565  0.820868

 [200 rows x 5 columns],
 'baseline_Adam_finetune_v4_composite_50_kl/':     patient_id  BG_Dice   LV_Dice  MYO_Dice   RV_Dice
 0       001_ED      0.0  0.957719  0.804758  0.887472
 1       002_ED      0.0  0.960758  0.799495  0.935182
 2       003_ED      0.0  0.966095  0.848534  0.906252
 3       004_ED      0.0  0.966635  0.840626  0.883729
 4       005_ED      0.0  0.959183  0.831893  0.903089
 ..         ...      ...       ...       ...       ...
 195     096_ES      0.0  0.877380  0.811579  0.904659
 196     097_ES      0.0  0.884493  0.799059  0.788844
 197     098_ES      0.0  0.850090  0.830393  0.923190
 198     099_ES      0.0  0.866057  0.777064  0.902603
 199     100_ES      0.0  0.860509  0.864831  0.835804

 [200 rows x 5 columns]}

In [26]:
## p_value

acdc_p_value= mt.p_value_test(reference_df = ACDC_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv'],test_df= ACDC_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_random'])
print ('ACDC',acdc_p_value)
ukbb_p_value = mt.p_value_test(reference_df = UKBB_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv'],test_df= UKBB_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_random'])
print('UKBB',ukbb_p_value)
MM_p_value = mt.p_value_test(reference_df = MM_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_adv'],test_df= MM_dfs['baseline_Adam_finetune_v4_composite_50_chain_mse_random'])
print('MM',MM_p_value)

ACDC {'LV_Dice': '0.0022', 'MYO_Dice': '0.0001', 'RV_Dice': '0.0596'}
UKBB {'LV_Dice': '0.1425', 'MYO_Dice': '0.0000', 'RV_Dice': '0.6409'}
MM {'LV_Dice': '0.2032', 'MYO_Dice': '0.0251', 'RV_Dice': '0.0000'}

In [ ]:
df.mean()

In [12]:
MM_dfs={}

In [14]:
## MM dataset
method_name = 'baseline_Adam_finetune_v4_composite_50_chain_mse_random' ##
MM_dfs={}
def evaluate_MM(method_name):
    gt_dir ='/vol/biomedic3/cc215/data/cardiac_MMSeg_challenge/Training-corrected/Labeled'
    gt_format='{pid}/sa_gt_{frame}.nrrd'

    pred_dir = '/vol/bitbucket/cc215/Projects/Cardiac_Multi_View_Segmentation/result/predict/{}/MM/LVSA/'.format(method_name)
    pred_format='{pid}/pred_{frame}.nrrd'
    df=evaluate(pred_dir,pred_format,gt_dir,gt_format)
    return df

method_name_list = [
                    'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_no_power',
                    # 'baseline_Adam_finetune_v4_composite_50_independent_mse_adv',
                    # 'baseline_Adam_finetune_v4_composite_50_kl',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_adv_random_select',
                    # 'baseline_Adam_finetune_v4_composite_50_chain_mse_random_random_select'

                     ]
for method_name in method_name_list:
    df = evaluate_MM(method_name)
    MM_dfs[method_name] = df



df.mean()

evaluate  A0S9V9 ED
evaluate  A1D0Q7 ED
evaluate  A1D9Z7 ED
evaluate  A1E9Q1 ED
evaluate  A1O8Z3 ED
evaluate  A2C0I1 ED
evaluate  A2N8V0 ED
evaluate  A3B7E5 ED
evaluate  A3H1O5 ED
evaluate  A4B5U4 ED
evaluate  A4J4S4 ED
evaluate  A4U9V5 ED
evaluate  A5E0T8 ED
evaluate  A6B5G9 ED
evaluate  A6D5F9 ED
evaluate  A6M1Q7 ED
evaluate  A7D9L8 ED
evaluate  A7G0P5 ED
evaluate  A7M7P8 ED
evaluate  A7O4T6 ED
evaluate  A8C9U8 ED
evaluate  A8E1F4 ED
evaluate  A9C5P4 ED
evaluate  A9E3G9 ED
evaluate  A9J5Q7 ED
evaluate  A9J8W7 ED
evaluate  B0I2Z0 ED
evaluate  B0N3W8 ED
evaluate  B2C2Z7 ED
evaluate  B2D9M2 ED
evaluate  B2D9O2 ED
evaluate  B2F4K5 ED
evaluate  B2G5R2 ED
evaluate  B3D0N1 ED
evaluate  B3O1S0 ED
evaluate  B3P3R1 ED
evaluate  B4O3V3 ED
evaluate  B6D0U7 ED
evaluate  B8H5H6 ED
evaluate  B8J7R4 ED
evaluate  B9E0Q1 ED
evaluate  B9O1Q0 ED
evaluate  C0K1P0 ED
evaluate  C0S7W0 ED
evaluate  C1G5Q0 ED
evaluate  C1K8P5 ED
evaluate  C2J0K3 ED
evaluate  C2L5P7 ED
evaluate  C2M6P8 ED
evaluate  C3I2K3 ED
evaluate  C4R8T7 ED
evaluate  C4S8W9 ED
evaluate  C5M4S2 ED
evaluate  C6J5P1 ED
evaluate  C8P3S7 ED
evaluate  D0H9I4 ED
evaluate  D0R0R9 ED
evaluate  D1J5P6 ED
evaluate  D1L4Q9 ED
evaluate  D1M1S6 ED
evaluate  D3D4Y5 ED
evaluate  D3F3O5 ED
evaluate  D3F9H9 ED
evaluate  D3O9U9 ED
evaluate  D4M3Q2 ED
evaluate  D4N6W6 ED
evaluate  D6H6O2 ED
evaluate  D8E4F4 ED
evaluate  D9L1Z3 ED
evaluate  E0M3U7 ED
evaluate  E0O0S0 ED
evaluate  E3T0Z2 ED
evaluate  E4M2Q7 ED
evaluate  E4W8Z7 ED
evaluate  E5E6O8 ED
evaluate  E5F5V7 ED
evaluate  E9H1U4 ED
evaluate  E9H2K7 ED
evaluate  E9L1W5 ED
evaluate  E9V4Z8 ED
evaluate  F0J2R8 ED
evaluate  F1F3I6 ED
evaluate  F2H5S1 ED
evaluate  F3G5K5 ED
evaluate  F4K3S1 ED
evaluate  F5I9Q2 ED
evaluate  F8N2S1 ED
evaluate  G0H4J3 ED
evaluate  G0I6P3 ED
evaluate  G1N6S7 ED
evaluate  G2J1M5 ED
evaluate  G2M7W4 ED
evaluate  G2O2S6 ED
evaluate  G4L8Z7 ED
evaluate  G4S9U3 ED
evaluate  G5P4U3 ED
evaluate  G7I5V7 ED
evaluate  G8N2U5 ED
evaluate  G9L0O9 ED
evaluate  H0K3Q4 ED
evaluate  H1I3W0 ED
evaluate  H1J5W8 ED
evaluate  H1M5Y6 ED
evaluate  H1W2Y1 ED
evaluate  H3U1Y1 ED
evaluate  H4I2T8 ED
evaluate  H5N0P0 ED
evaluate  H6I0I6 ED
evaluate  H7I4J3 ED
evaluate  H7N4V9 ED
evaluate  I0J5U3 ED
evaluate  I2K2Y8 ED
evaluate  I6N3P3 ED
evaluate  I7T3U1 ED
evaluate  J1T9Y1 ED
evaluate  J4J9W6 ED
evaluate  J6K6P5 ED
evaluate  J6P5T8 ED
evaluate  J8R5W2 ED
evaluate  J9L6N9 ED
evaluate  K2S1U6 ED
evaluate  K4T7Y0 ED
evaluate  K5L2U3 ED
evaluate  K5P0Y1 ED
evaluate  L1Q1Z5 ED
evaluate  L1Q9V8 ED
evaluate  L4Q2U3 ED
evaluate  L5Q6T7 ED
evaluate  M0P8U8 ED
evaluate  M1R4S1 ED
evaluate  M2P1R1 ED
evaluate  M4P7Q6 ED
evaluate  N1P8Q9 ED
evaluate  N5S7Y1 ED
evaluate  N7V9W9 ED
evaluate  N8N9U0 ED
evaluate  O0S9V7 ED
evaluate  O3R8Y5 ED
evaluate  P0S5Y0 ED
evaluate  P5R1Y4 ED
evaluate  P6U0Y0 ED
evaluate  P9S7W2 ED
evaluate  Q0U0V5 ED
evaluate  Q3R9W7 ED
evaluate  Q7V1Y5 ED
evaluate  R4Y1Z9 ED
evaluate  S1S3Z7 ED
evaluate  T2T9Z9 ED
evaluate  T9U9W2 ED
evaluate  W5Z4Z8 ED
evaluate  A0S9V9 ES
evaluate  A1D0Q7 ES
evaluate  A1D9Z7 ES
evaluate  A1E9Q1 ES
evaluate  A1O8Z3 ES
evaluate  A2C0I1 ES
evaluate  A2N8V0 ES
evaluate  A3B7E5 ES
evaluate  A3H1O5 ES
evaluate  A4B5U4 ES
evaluate  A4J4S4 ES
evaluate  A4U9V5 ES
evaluate  A5E0T8 ES
evaluate  A6B5G9 ES
evaluate  A6D5F9 ES
evaluate  A6M1Q7 ES
evaluate  A7D9L8 ES
evaluate  A7G0P5 ES
evaluate  A7M7P8 ES
evaluate  A7O4T6 ES
evaluate  A8C9U8 ES
evaluate  A8E1F4 ES
evaluate  A9C5P4 ES
evaluate  A9E3G9 ES
evaluate  A9J5Q7 ES
evaluate  A9J8W7 ES
evaluate  B0I2Z0 ES
evaluate  B0N3W8 ES
evaluate  B2C2Z7 ES
evaluate  B2D9M2 ES
evaluate  B2D9O2 ES
evaluate  B2F4K5 ES
evaluate  B2G5R2 ES
evaluate  B3D0N1 ES
evaluate  B3O1S0 ES
evaluate  B3P3R1 ES
evaluate  B4O3V3 ES
evaluate  B6D0U7 ES
evaluate  B8H5H6 ES
evaluate  B8J7R4 ES
evaluate  B9E0Q1 ES
evaluate  B9O1Q0 ES
evaluate  C0K1P0 ES
evaluate  C0S7W0 ES
evaluate  C1G5Q0 ES
evaluate  C1K8P5 ES
evaluate  C2J0K3 ES
evaluate  C2L5P7 ES
evaluate  C2M6P8 ES
evaluate  C3I2K3 ES
evaluate  C4R8T7 ES
evaluate  C4S8W9 ES
evaluate  C5M4S2 ES
evaluate  C6J5P1 ES
evaluate  C8P3S7 ES
evaluate  D0H9I4 ES
evaluate  D0R0R9 ES
evaluate  D1J5P6 ES
evaluate  D1L4Q9 ES
evaluate  D1M1S6 ES
evaluate  D3D4Y5 ES
evaluate  D3F3O5 ES
evaluate  D3F9H9 ES
evaluate  D3O9U9 ES
evaluate  D4M3Q2 ES
evaluate  D4N6W6 ES
evaluate  D6H6O2 ES
evaluate  D8E4F4 ES
evaluate  D9L1Z3 ES
evaluate  E0M3U7 ES
evaluate  E0O0S0 ES
evaluate  E3T0Z2 ES
evaluate  E4M2Q7 ES
evaluate  E4W8Z7 ES
evaluate  E5E6O8 ES
evaluate  E5F5V7 ES
evaluate  E9H1U4 ES
evaluate  E9H2K7 ES
evaluate  E9L1W5 ES
evaluate  E9V4Z8 ES
evaluate  F0J2R8 ES
evaluate  F1F3I6 ES
evaluate  F2H5S1 ES
evaluate  F3G5K5 ES
evaluate  F4K3S1 ES
evaluate  F5I9Q2 ES
evaluate  F8N2S1 ES
evaluate  G0H4J3 ES
evaluate  G0I6P3 ES
evaluate  G1N6S7 ES
evaluate  G2J1M5 ES
evaluate  G2M7W4 ES
evaluate  G2O2S6 ES
evaluate  G4L8Z7 ES
evaluate  G4S9U3 ES
evaluate  G5P4U3 ES
evaluate  G7I5V7 ES
evaluate  G8N2U5 ES
evaluate  G9L0O9 ES
evaluate  H0K3Q4 ES
evaluate  H1I3W0 ES
evaluate  H1J5W8 ES
evaluate  H1M5Y6 ES
evaluate  H1W2Y1 ES
evaluate  H3U1Y1 ES
evaluate  H4I2T8 ES
evaluate  H5N0P0 ES
evaluate  H6I0I6 ES
evaluate  H7I4J3 ES
evaluate  H7N4V9 ES
evaluate  I0J5U3 ES
evaluate  I2K2Y8 ES
evaluate  I6N3P3 ES
evaluate  I7T3U1 ES
evaluate  J1T9Y1 ES
evaluate  J4J9W6 ES
evaluate  J6K6P5 ES
evaluate  J6P5T8 ES
evaluate  J8R5W2 ES
evaluate  J9L6N9 ES
evaluate  K2S1U6 ES
evaluate  K4T7Y0 ES
evaluate  K5L2U3 ES
evaluate  K5P0Y1 ES
evaluate  L1Q1Z5 ES
evaluate  L1Q9V8 ES
evaluate  L4Q2U3 ES
evaluate  L5Q6T7 ES
evaluate  M0P8U8 ES
evaluate  M1R4S1 ES
evaluate  M2P1R1 ES
evaluate  M4P7Q6 ES
evaluate  N1P8Q9 ES
evaluate  N5S7Y1 ES
evaluate  N7V9W9 ES
evaluate  N8N9U0 ES
evaluate  O0S9V7 ES
evaluate  O3R8Y5 ES
evaluate  P0S5Y0 ES
evaluate  P5R1Y4 ES
evaluate  P6U0Y0 ES
evaluate  P9S7W2 ES
evaluate  Q0U0V5 ES
evaluate  Q3R9W7 ES
evaluate  Q7V1Y5 ES
evaluate  R4Y1Z9 ES
evaluate  S1S3Z7 ES
evaluate  T2T9Z9 ES
evaluate  T9U9W2 ES
evaluate  W5Z4Z8 ES
({'BG_Dice_mean': 0.0, 'BG_Dice_std': 0.0, 'LV_Dice_mean': 0.8929243229179123, 'LV_Dice_std': 0.07476266229642758, 'MYO_Dice_mean': 0.7986725857810266, 'MYO_Dice_std': 0.0768845451059056, 'RV_Dice_mean': 0.8244713067993076, 'RV_Dice_std': 0.12387807393053266}, [['0.000', '0.893', '0.799', '0.824'], ['0.000', '0.075', '0.077', '0.124']], ['BG_Dice', 'LV_Dice', 'MYO_Dice', 'RV_Dice'])

NameError: name 'MM_dfs' is not defined

In [15]:
MM_dfs[method_name]=df
df.describe()

       BG_Dice     LV_Dice    MYO_Dice     RV_Dice
count    300.0  300.000000  300.000000  300.000000
mean       0.0    0.875117    0.766908    0.824853
std        0.0    0.119429    0.113244    0.119989
min        0.0    0.000000    0.000000    0.183657
25%        0.0    0.857906    0.735551    0.799986
50%        0.0    0.906018    0.790092    0.858719
75%        0.0    0.939673    0.833039    0.896651
max        0.0    0.981484    0.892920    0.967891

       BG_Dice     LV_Dice    MYO_Dice     RV_Dice
count    300.0  300.000000  300.000000  300.000000
mean       0.0    0.893491    0.802149    0.835294
std        0.0    0.074856    0.068768    0.102410
min        0.0    0.154555    0.240272    0.062953
25%        0.0    0.874611    0.773181    0.798983
50%        0.0    0.908166    0.813498    0.863184
75%        0.0    0.938024    0.846573    0.898019
max        0.0    0.982844    0.895662    0.966797

In [ ]:
df.describe()